#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sWebSteelDesigner
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SteelDesigner")]
	public partial class SteelDesiDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClientInfo(ClientInfo instance);
    partial void UpdateClientInfo(ClientInfo instance);
    partial void DeleteClientInfo(ClientInfo instance);
    #endregion
		
		public SteelDesiDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SteelDesignerConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SteelDesiDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SteelDesiDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SteelDesiDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SteelDesiDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClientInfo> ClientInfos
		{
			get
			{
				return this.GetTable<ClientInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientInfo")]
	public partial class ClientInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.Guid> _clientInfoID;
		
		private string _clientFirmName;
		
		private string _clientEmail;
		
		private string _clientFirstName;
		
		private string _clientLastName;
		
		private string _clientOccupation;
		
		private string _clientComment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclientInfoIDChanging(System.Nullable<System.Guid> value);
    partial void OnclientInfoIDChanged();
    partial void OnclientFirmNameChanging(string value);
    partial void OnclientFirmNameChanged();
    partial void OnclientEmailChanging(string value);
    partial void OnclientEmailChanged();
    partial void OnclientFirstNameChanging(string value);
    partial void OnclientFirstNameChanged();
    partial void OnclientLastNameChanging(string value);
    partial void OnclientLastNameChanged();
    partial void OnclientOccupationChanging(string value);
    partial void OnclientOccupationChanged();
    partial void OnclientCommentChanging(string value);
    partial void OnclientCommentChanged();
    #endregion
		
		public ClientInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientInfoID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> clientInfoID
		{
			get
			{
				return this._clientInfoID;
			}
			set
			{
				if ((this._clientInfoID != value))
				{
					this.OnclientInfoIDChanging(value);
					this.SendPropertyChanging();
					this._clientInfoID = value;
					this.SendPropertyChanged("clientInfoID");
					this.OnclientInfoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientFirmName", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string clientFirmName
		{
			get
			{
				return this._clientFirmName;
			}
			set
			{
				if ((this._clientFirmName != value))
				{
					this.OnclientFirmNameChanging(value);
					this.SendPropertyChanging();
					this._clientFirmName = value;
					this.SendPropertyChanged("clientFirmName");
					this.OnclientFirmNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientEmail", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string clientEmail
		{
			get
			{
				return this._clientEmail;
			}
			set
			{
				if ((this._clientEmail != value))
				{
					this.OnclientEmailChanging(value);
					this.SendPropertyChanging();
					this._clientEmail = value;
					this.SendPropertyChanged("clientEmail");
					this.OnclientEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientFirstName", DbType="VarChar(50)")]
		public string clientFirstName
		{
			get
			{
				return this._clientFirstName;
			}
			set
			{
				if ((this._clientFirstName != value))
				{
					this.OnclientFirstNameChanging(value);
					this.SendPropertyChanging();
					this._clientFirstName = value;
					this.SendPropertyChanged("clientFirstName");
					this.OnclientFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientLastName", DbType="VarChar(50)")]
		public string clientLastName
		{
			get
			{
				return this._clientLastName;
			}
			set
			{
				if ((this._clientLastName != value))
				{
					this.OnclientLastNameChanging(value);
					this.SendPropertyChanging();
					this._clientLastName = value;
					this.SendPropertyChanged("clientLastName");
					this.OnclientLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientOccupation", DbType="VarChar(100)")]
		public string clientOccupation
		{
			get
			{
				return this._clientOccupation;
			}
			set
			{
				if ((this._clientOccupation != value))
				{
					this.OnclientOccupationChanging(value);
					this.SendPropertyChanging();
					this._clientOccupation = value;
					this.SendPropertyChanged("clientOccupation");
					this.OnclientOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clientComment", DbType="VarChar(MAX)")]
		public string clientComment
		{
			get
			{
				return this._clientComment;
			}
			set
			{
				if ((this._clientComment != value))
				{
					this.OnclientCommentChanging(value);
					this.SendPropertyChanging();
					this._clientComment = value;
					this.SendPropertyChanged("clientComment");
					this.OnclientCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
